### ISSUE TITLE
Content editor toolbar is hidden by admin header

### ISSUE THREAD

**Issue by mikkamp** [woocommerce/woocommerce-admin#2337]
**Describe the bug**
The admin header is added to every WooCommerce page, including when we are editing products. However WordPress has a feature to show a sticky header when editing the content. This is especially apparant with products that have a lot of text content.
Which means as soon as we need to use the toolbar or the add media button when editing the content we need to scroll all the way up again.

**To Reproduce**

1. Go to edit a product, and add a large amount of text content
2. Make sure the screen option "Enable full-height editor and distraction-free functionality" is turned on.
3. Scroll down to the bottom of the product text content
4. Observe the toolbar is hidden

**Expected behavior**
I would expect the editing toolbar to take priority. Or alternatively have a way to disable the admin header so it doesn't show up on some page, like when editing products.

**Screenshots**
Here is an example of the toolbar being hidden when editing the product content:
![image](https://user-images.githubusercontent.com/11388669/58559100-4468f300-821a-11e9-9abe-775344dc9714.png)

Here is the same example with the admin plugin deactivated:
![image](https://user-images.githubusercontent.com/11388669/58559117-521e7880-821a-11e9-93cc-f1183603cbb6.png)

**Comment by timmyc** [comment]
Thanks for the report @mikkamp

**Comment by CharlieEtienne** [comment]
I suggest to use this CSS style when page is scrolled:

```css
@media (min-width: 783px){
    .woocommerce-embed-page .woocommerce-layout__header.is-scrolled,
    .woocommerce-layout__header.is-scrolled .woocommerce-layout__header-breadcrumbs,
    .woocommerce-layout__header.is-scrolled .woocommerce-layout__activity-panel,
    .woocommerce-layout__header.is-scrolled .woocommerce-layout__activity-panel-tabs,
    .woocommerce-layout__header.is-scrolled .woocommerce-layout__activity-panel-tabs .woocommerce-layout__activity-panel-tab {
        height: 50px;
    }
    .woocommerce-layout__header.is-scrolled .woocommerce-layout__header-breadcrumbs {
        line-height: 50px;
    }
    .woocommerce-layout__header.is-scrolled .woocommerce-layout__activity-panel-tabs .woocommerce-layout__activity-panel-tab {
        font-size:11px;
    }
    .woocommerce-layout__header.is-scrolled .woocommerce-layout__activity-panel-tabs svg {
        width: 18px;
        height: 18px;
    }
}
```
